version: "3.9"

services:
  api:
    container_name: api_platforma
    build:
      dockerfile: Dockerfile.prod
      context: .
    restart: always
    ports:
          - "8000:8000"
    env_file: ".env"